import {useMemo,useState} from 'react';
import type {SeriesNacionales,PoblacionAnual,EstatalAnual,MunicipalAnual,Manifiesto} from '../lib/contratos';
import {calendario,mesesCortos,administraciones,serieMandato} from '../lib/laboratorio';
import {descargarCSV} from '../lib/datos';
import Grafica from './Grafica';
import {colorDelito} from '../theme/paleta';
import '../laboratorio.css';
const f=(v:number|null|undefined)=>v==null?'Sin información':v.toLocaleString('es-MX',{maximumFractionDigits:1});
const pendientes=[
 ['Reconocimiento feminicida','Víctimas por sexo y población femenina','Integrar víctimas del SESNSP y mortalidad INEGI por separado. La base de delitos actual no permite inferir el sexo de víctimas de homicidio.','https://www.inegi.org.mx/programas/edr/'],
 ['Proyección 2026','Homologación validada y evaluación temporal','Una banda requiere un modelo evaluado fuera de muestra. No se empalman instrumentos ni se presenta una media móvil como intervalo probabilístico.','https://www.gob.mx/sesnsp'],
 ['Cambios estructurales','Modelo reproducible e incertidumbre','El máximo de una serie no es un quiebre estadístico; no se asignan fechas ni p-valores sin estimación.','https://www.gob.mx/sesnsp'],
 ['Asociación espacial','Matriz de vecindad y pruebas locales','Moran global no localiza por sí solo conglomerados; LISA requiere pruebas múltiples. No demuestra desplazamiento delictivo.','https://www.inegi.org.mx/temas/mg/'],
 ['Contexto socioeconómico','Series armonizadas por territorio y año','Pobreza, empleo y actividad económica no comparten necesariamente frecuencia ni cobertura. Correlación no identifica causas.','https://www.inegi.org.mx/'],
 ['Comparación internacional','Homicidio intencional compatible','Comparar países con igual periodo y unidad; separar el contexto municipal por su escala y volatilidad.','https://dataunodc.un.org/'],
 ['Agrupamientos municipales','Categorías y estabilidad de grupos','UMAP reduce dimensiones; no sustituye un algoritmo de agrupamiento. No se infieren perfiles criminales por nombres de municipios.','https://www.gob.mx/sesnsp'],
 ['Presupuesto y seguridad','Gasto ejercido real y cobertura fiscal','FASP no representa todo el gasto. Gasto por delito registrado no demuestra eficiencia institucional.','https://www.transparenciapresupuestaria.gob.mx/'],
];
const temas=[['zafiro','Grafito y zafiro'],['oceano','Azul Oceánico'],['indigo','Índigo Forense'],['carbon','Carbón Institucional'],['pizarra','Pizarra Analítica'],['esmeralda','Obsidiana · Esmeralda']];
export default function Laboratorio({nm,nr,pob,estatal,municipal,manifiesto}:{nm:SeriesNacionales;nr:SeriesNacionales|null;pob:PoblacionAnual;estatal:EstatalAnual;municipal:MunicipalAnual;manifiesto:Manifiesto}){
 const [instrumento,setInstrumento]=useState('nm'),[id,setId]=useState('homicidio-doloso'),[vista,setVista]=useState('calendario'),[modo,setModo]=useState('diario'),[celda,setCelda]=useState(''),[seleccion,setSeleccion]=useState(['01','09']),[anio,setAnio]=useState(2025),[busqueda,setBusqueda]=useState(''),[tema,setTema]=useState('zafiro');
 const sn=instrumento==='nr'&&nr?nr:nm,ids=Object.keys(sn.series).filter(k=>!k.includes('/')).sort(),delito=id==='total'||ids.includes(id)?id:ids[0],nombre=delito==='total'?'Todos los delitos':sn.jerarquia[delito]?.subtipo??delito;
 const celdas=useMemo(()=>calendario(sn,delito,modo),[sn,delito,modo]);const max=Math.max(1,...celdas.map(c=>Math.abs(c.valor??0))),anos=[...new Set(celdas.map(c=>c.fecha.slice(0,4)))];
 const etiquetaUnidad=modo==='conteo'?'delitos registrados':modo==='diario'?'registros por día':'% frente al promedio diario del mismo mes en años completos';
 const exportar=(titulo:string,headers:string[],filas:(string|number|null)[][],unidad:string,extra:Record<string,string>={})=>descargarCSV(titulo+'.csv',headers,filas,{fuente:sn.meta.fuente,corte:sn.meta.corte,version:String(sn.meta.version),instrumento:sn.metodologia,delito:nombre,unidad,...extra});
 const fechas=sn.meses;const filasComposicion=Object.entries(sn.series).filter(([k])=>!k.includes('/')).map(([k,vs])=>({id:k,nombre:sn.jerarquia[k]?.subtipo??k,total:vs.every(v=>v!=null&&v>=0)?vs.reduce<number>((s,v)=>s+v!,0):null})).sort((a,b)=>(b.total??-1)-(a.total??-1));
 const total=sn.total.every(v=>v!=null&&v>=0)?sn.total.reduce<number>((a,b)=>a+b!,0):null;
 const concilia=total!=null&&filasComposicion.every(x=>x.total!=null)&&filasComposicion.reduce((a,x)=>a+x.total!,0)===total;
 const ia=estatal.anios.indexOf(anio),tipos=Object.keys(estatal.datos['01']??{}).filter(k=>Object.keys(estatal.entidades).every(c=>estatal.datos[c]?.[k]?.[ia]!=null)).slice(0,8);
 const perfil=tipos.map(k=>({id:k,nombre:nm.jerarquia[k]?.subtipo??k,valores:seleccion.map(c=>{const p=pob.estatal[c]?.[anio],v=estatal.datos[c]?.[k]?.[ia];return p>0&&v!=null&&v>=0?v/p*1e5:null;})}));
 const anosMunicipales=municipal.anios.filter(a=>a<=2025&&a>=2021),indices=anosMunicipales.map(a=>municipal.anios.indexOf(a));
 const trayectorias=municipal.municipios.filter(m=>indices.every(i=>m.total[i]!=null&&m.total[i]!>=0)).map(m=>{const valores=indices.map(i=>m.total[i]!),cambios=valores.slice(1).map((v,i)=>v-valores[i]);return {...m,valores,perfil:cambios.length&&cambios.every(v=>v<0)?'Descenso sostenido':cambios.length&&cambios.every(v=>v>0)?'Aumento sostenido':cambios.every(v=>v===0)?'Sin cambio':'Fluctuación'};}).filter(m=>`${m.nombre} ${m.entidad}`.toLocaleLowerCase().includes(busqueda.toLocaleLowerCase())).sort((a,b)=>b.valores.at(-1)!-a.valores.at(-1)!);
 const tabs=[['calendario','Calendario mensual'],['mandatos','Administraciones'],['composicion','Composición'],['perfil','Perfiles estatales'],['trayectorias','Trayectorias municipales'],['revision','Revisiones'],['fuentes','Nuevas fuentes']];
 return <section id="laboratorio" className="seccion ni-lab" aria-labelledby="titulo-lab">
  <div className="ni-lab-hero"><p className="ni-eyebrow">Neural Network Initiative / LABORATORIO DE EVIDENCIA</p><h2 id="titulo-lab">Más preguntas.<br/><span>Mejores comparaciones.</span></h2><p>Explora patrones, contrasta ventanas y consulta lo que los datos permiten afirmar.</p><label>Ambiente visual <select value={tema} onChange={e=>{setTema(e.target.value);document.documentElement.dataset.paleta=e.target.value;}}>{temas.map(([k,n])=><option value={k} key={k}>{n}</option>)}</select></label><small>La paleta cambia superficies y selección. Los colores estadísticos conservan su significado.</small></div>
  <nav className="ni-preguntas" aria-label="Cinco recorridos analíticos">{[['#territorio-impacto','01','¿Dónde ocurre el cambio?'],['#alto-impacto','02','¿Resiste la comparación?'],['#fuentes-pendientes','03','Reconocimiento feminicida'],['#laboratorio','04','¿Se sostiene y se extiende?'],['#alto-impacto','05','Registro y victimización']].map(([href,n,t])=><a href={href} key={n} onClick={()=>{if(n==='04')setVista('trayectorias');if(n==='03')setVista('fuentes');}}><span>{n}</span><strong>{t}</strong><small>{n==='03'?'Requiere nuevas fuentes':'Explorar evidencia →'}</small></a>)}</nav>
  <div className="ni-tabs" role="group" aria-label="Análisis disponibles">{tabs.map(([k,n])=><button key={k} aria-pressed={vista===k} onClick={()=>{setVista(k);if(k!=='calendario'&&modo==='patron')setModo('diario');}}>{n}</button>)}</div>
  {['calendario','mandatos','composicion'].includes(vista)&&<div className="ni-controls"><label>Instrumento<select value={instrumento} onChange={e=>setInstrumento(e.target.value)}><option value="nm">2015–2025</option><option value="nr" disabled={!nr}>RNID desde 2026</option></select></label><label>Delito<select value={delito} onChange={e=>setId(e.target.value)}><option value="total">Todos los delitos</option>{ids.map(k=><option key={k} value={k}>{sn.jerarquia[k]?.subtipo??k}</option>)}</select></label><label>Métrica<select value={modo} onChange={e=>setModo(e.target.value)}><option value="diario">Promedio diario</option><option value="conteo">Cantidad</option>{vista==='calendario'&&<option value="patron">Desviación del patrón mensual</option>}</select></label><p>Filtros locales · {sn.metodologia} · corte {sn.meta.corte}</p></div>}
  {vista==='calendario'&&<article className="tarjeta ni-panel"><h3>El tiempo deja patrones</h3><p>{nombre} · {etiquetaUnidad}. Cada celda representa un mes; no se inventan observaciones diarias.</p><div className="ni-calendar" role="group" aria-label="Calendario de meses"><span>Año</span>{mesesCortos.map(m=><span key={m}>{m}</span>)}{anos.map(a=><div className="ni-year" key={a}><strong>{a}</strong>{celdas.filter(c=>c.fecha.startsWith(a)).map(c=><button key={c.fecha} className={c.valor==null?'ni-missing':''} aria-label={`${c.fecha}: ${f(c.valor)} ${etiquetaUnidad}`} aria-pressed={celda===c.fecha} style={c.valor==null?{}:{background:modo==='patron'?(c.valor<0?'#305D58':'#71524C'):`rgba(59,130,246,${.18+.8*Math.abs(c.valor)/max})`}} onClick={()=>setCelda(c.fecha)}>{c.valor==null?'—':Number(c.fecha.slice(5))}</button>)}</div>)}</div><p role="status">{celda?`${celda}: ${f(celdas.find(c=>c.fecha===celda)?.valor)} ${etiquetaUnidad}`:'Toca un mes o selecciónalo con el teclado para consultar su valor.'}</p><small>Más intensidad = mayor cantidad o promedio diario. En desviaciones: turquesa = por debajo; terracota = por encima. Trama = sin dato o referencia insuficiente. El patrón usa solo años completos del instrumento.</small><Grafica ariaLabel={`Serie mensual de ${nombre}`} opcion={{xAxis:{type:'category',data:sn.meses},yAxis:{type:'value'},series:[{type:'line',data:celdas.filter(c=>sn.meses.includes(c.fecha)).map(c=>c.valor),connectNulls:false,symbolSize:4}],dataZoom:[{type:'inside'},{type:'slider'}]}}/><button onClick={()=>exportar('calendario',['mes','valor','referencia_diaria'],celdas.map(c=>[c.fecha,c.valor,c.referencia]),etiquetaUnidad)}>Descargar calendario</button><details><summary>Ver tabla accesible</summary><div className="ni-table"><table><thead><tr><th>Mes</th><th>Valor</th></tr></thead><tbody>{celdas.map(c=><tr key={c.fecha}><td>{c.fecha}</td><td>{f(c.valor)}</td></tr>)}</tbody></table></div></details></article>}
  {vista==='mandatos'&&<article className="tarjeta ni-panel"><h3>Mismo mes de gobierno, cobertura visible</h3><p>Las curvas muestran un solo instrumento. Peña Nieto tiene datos desde su mes 26, no desde su toma de posesión. No hay datos de Calderón en esta base.</p><Grafica ariaLabel="Series por mes de administración" opcion={{legend:{data:administraciones.map(a=>a.nombre)},xAxis:{type:'category',name:'Mes de mandato',data:Array.from({length:72},(_,i)=>i+1)},yAxis:{type:'value',name:modo==='conteo'?'Registros':'Registros/día'},series:administraciones.map(a=>({name:a.nombre,type:'line',connectNulls:false,data:serieMandato(sn,delito,a.desde,a.hasta,modo!=='conteo')}))}}/><p>Comparación descriptiva: la alineación no controla estacionalidad, contexto ni identifica efectos de gobierno.</p><button onClick={()=>exportar('administraciones',['administracion','inicio','mes_mandato','valor'],administraciones.flatMap(a=>serieMandato(sn,delito,a.desde,a.hasta,modo!=='conteo').map((v,i)=>[a.nombre,a.desde,i+1,v])),modo==='conteo'?'registros':'registros/día')}>Descargar comparación</button><details><summary>Fechas y tabla de cobertura</summary>{administraciones.map(a=><p key={a.nombre}>{a.nombre}: {a.desde}. {serieMandato(sn,delito,a.desde,a.hasta,false).filter(v=>v!=null).length} meses disponibles en este instrumento.</p>)}<a href="https://www.diputados.gob.mx/LeyesBiblio/ref/cpeum.htm" target="_blank" rel="noreferrer">Marco constitucional y reformas · Cámara de Diputados</a></details></article>}
  {vista==='composicion'&&<article className="tarjeta ni-panel"><h3>La composición del registro</h3><p>Todos los delitos del instrumento, {fechas[0]}–{fechas.at(-1)}. El selector individual y la métrica diaria no se aplican a esta distribución de cantidades.</p>{concilia?<><p><strong>{f(total)}</strong> registros · categorías conciliadas con el total nacional.</p><div className="ni-table"><table><thead><tr><th>Categoría</th><th>Registros</th><th>Participación</th></tr></thead><tbody>{filasComposicion.map(x=><tr key={x.id}><td><span className="punto" style={{background:colorDelito(x.id)}}/> {x.nombre}</td><td>{f(x.total)}</td><td><meter min={0} max={100} value={total?100*x.total!/total:0}/>{total?f(100*x.total!/total)+' %':'No definida'}</td></tr>)}</tbody></table></div><button onClick={()=>exportar('composicion',['categoria','cantidad','participacion_pct'],filasComposicion.map(x=>[x.nombre,x.total,total?100*x.total!/total:null]),'delitos registrados',{delito:'Todos los delitos'})}>Descargar composición</button></>:<p role="status">No se presenta composición: faltan valores o las categorías no concilian con el total.</p>}</article>}
  {vista==='perfil'&&<article className="tarjeta ni-panel"><h3>Perfiles estatales sin perder la escala</h3><p>Hasta tres entidades · tasas por 100 mil habitantes · categorías disponibles. No es un índice de gravedad.</p><label>Año completo<select value={anio} onChange={e=>setAnio(Number(e.target.value))}>{estatal.anios.filter(a=>a<=2025&&estatal.meses_publicados[a]===12).map(a=><option key={a}>{a}</option>)}</select></label><fieldset><legend>Selecciona hasta tres entidades</legend><div className="ni-entidades">{Object.entries(estatal.entidades).map(([c,n])=><label key={c}><input type="checkbox" checked={seleccion.includes(c)} disabled={!seleccion.includes(c)&&seleccion.length>=3} onChange={()=>setSeleccion(seleccion.includes(c)?seleccion.filter(x=>x!==c):[...seleccion,c])}/>{n}</label>)}</div></fieldset><Grafica ariaLabel="Comparación de tasas por categoría y entidad" opcion={{legend:{data:seleccion.map(c=>estatal.entidades[c])},grid:{left:180,right:25,bottom:50,top:45},yAxis:{type:'category',data:perfil.map(x=>x.nombre)},xAxis:{type:'value',name:'Por 100 mil habitantes'},series:seleccion.map((c,i)=>({name:estatal.entidades[c],type:'bar',data:perfil.map(x=>x.valores[i])}))}}/><div className="ni-table"><table><thead><tr><th>Categoría</th>{seleccion.map(c=><th key={c}>{estatal.entidades[c]}</th>)}</tr></thead><tbody>{perfil.map(x=><tr key={x.id}><th>{x.nombre}</th>{x.valores.map((v,i)=><td key={i}>{f(v)}</td>)}</tr>)}</tbody></table></div><button onClick={()=>exportar('perfiles',['categoria',...seleccion.map(c=>estatal.entidades[c])],perfil.map(x=>[x.nombre,...x.valores]),'delitos por 100 mil habitantes',{fuente:estatal.meta.fuente,instrumento:estatal.metodologia,delito:'Ocho categorías estatales disponibles',anio:String(anio),poblacion:pob.meta.fuente})}>Descargar perfiles</button></article>}
  {vista==='trayectorias'&&<article className="tarjeta ni-panel"><h3>¿La reducción se sostiene?</h3><p>Todos los delitos · {anosMunicipales.join(', ')} · cantidades anuales completas. Descenso/aumento sostenido exige que todas las variaciones consecutivas tengan el mismo signo. No mide riesgo individual ni identifica focos por tasa.</p><label>Buscar municipio o entidad<input type="search" value={busqueda} onChange={e=>setBusqueda(e.target.value)}/></label><p>{trayectorias.length} municipios con datos completos coinciden. Se muestran los primeros 100 por cantidad del último año; el CSV incluye todos los coincidentes.</p><div className="ni-table"><table><thead><tr><th>Municipio</th>{anosMunicipales.map(a=><th key={a}>{a}</th>)}<th>Trayectoria</th></tr></thead><tbody>{trayectorias.slice(0,100).map(m=><tr key={m.cve}><th>{m.nombre} · {m.entidad}</th>{m.valores.map((v,i)=><td key={i}>{f(v)}</td>)}<td>{m.perfil}</td></tr>)}</tbody></table></div><button onClick={()=>exportar('trayectorias',['clave','municipio','entidad',...anosMunicipales.map(String),'trayectoria'],trayectorias.map(m=>[m.cve,m.nombre,m.entidad,...m.valores,m.perfil]),'delitos registrados',{fuente:municipal.meta.fuente,delito:'Todos los delitos',instrumento:'NM-2015',busqueda})}>Descargar trayectorias</button></article>}
  {vista==='revision'&&<article className="tarjeta ni-panel"><h3>Qué cambió entre publicaciones</h3><p>Consulta a la fuente: {manifiesto.ultima_consulta_fuente??'No disponible'}<br/>Última actualización validada: {manifiesto.ultima_actualizacion_validada??'No disponible'}</p>{manifiesto.cambios.map((c,i)=><div className="ni-revision" key={i}><time>{c.ts}</time><strong>{c.evento}</strong><p>{c.detalle}</p></div>)}<p>El historial disponible no permite reconstruir revisiones anteriores a la primera captura. No se presentan diferencias estadísticas entre instantáneas sin ambas versiones.</p><details><summary>Huellas de los originales publicados</summary>{manifiesto.fuentes.map(s=><p key={s.clave}>{s.descripcion}<br/><code>{s.sha256}</code></p>)}</details></article>}
  {vista==='fuentes'&&<article className="ni-panel" id="fuentes-pendientes"><h3>Qué falta para responder otras preguntas</h3><p>Estos análisis todavía no calculan resultados. Las fuentes enlazadas son puntos de partida, no conjuntos ya integrados.</p><div className="ni-pending">{pendientes.map(([t,d,l,url])=><article className="tarjeta" key={t}><span className="ni-status">Pendiente de integración</span><h4>{t}</h4><strong>{d}</strong><p>{l}</p><a href={url} target="_blank" rel="noreferrer">Consultar fuente oficial ↗</a></article>)}</div></article>}
 </section>;
}
