import CambioVisual from "./CambioVisual";
import { useEffect,useState } from 'react';
import type { EstatalAnual,SeriesNacionales,PoblacionAnual } from '../lib/contratos';
import { descomponer } from '../lib/territorial';
import { cambio, PRIORITARIOS } from '../lib/altoImpacto';
import { cargar,descargarCSV } from '../lib/datos';
import type { GeoColeccion } from '../lib/geo';
import MapaMx from './MapaMx';
const f=(v:number|null|undefined)=>v==null?'Sin datos':v.toLocaleString('es-MX',{maximumFractionDigits:1});
export default function TerritorioImpacto({estatal,sn,pob}:{estatal:EstatalAnual;sn:SeriesNacionales;pob:PoblacionAnual}){
 const ids=PRIORITARIOS.filter(id=>Object.values(estatal.datos).every(d=>d[id])&&sn.series[id]);
 const [id,setId]=useState('robo-de-vehiculo-automotor'),[base,setBase]=useState(2024),[actual,setActual]=useState(2025),[modo,setModo]=useState<'2d'|'3d'>('2d'),[tasa,setTasa]=useState(false),[geo,setGeo]=useState<GeoColeccion|null>(null);
 useEffect(()=>{cargar<GeoColeccion>('geo/estados.json').then(setGeo).catch(()=>setGeo(null));},[]);
 const delito=ids.includes(id)?id:ids[0],r=descomponer(estatal,sn,delito,base,actual);
 const años=estatal.anios.filter(y=>y<=2025&&estatal.meses_publicados[String(y)]===12);
 const tasaAnual=(cve:string,v:number|null|undefined,y:number)=>v==null||!pob.estatal[cve]?.[String(y)]?null:v/pob.estatal[cve][String(y)]*100000;
 const filas=r?[...r.filas].sort((a,b)=>a.diferencia!-b.diferencia!):[];
 const [verCambio,setVerCambio]=useState(false);
 const valores=Object.fromEntries(filas.map(x=>[x.cve,{v:verCambio?x.diferencia??null:tasa?tasaAnual(x.cve,x.actual,actual):x.actual??null}]));
 return <section className="seccion" id="territorio-impacto"><div className="seccion__head"><h2>¿Dónde cambia el registro?</h2></div><p className="seccion__desc">Descomposición estatal de las categorías prioritarias disponibles. Años completos de 2015–2025. Homicidio, feminicidio, extorsión y secuestro todavía no tienen desglose estatal en este producto: no se sustituyen por el total de delitos.</p>
 <div className="impacto-controles"><label>Delito territorial<select className="control" value={delito} onChange={e=>setId(e.target.value)}>{ids.map(k=><option key={k} value={k}>{sn.jerarquia[k].subtipo}</option>)}</select></label><label>Año base<select className="control" value={base} onChange={e=>setBase(Number(e.target.value))}>{años.filter(y=>y<actual).map(y=><option key={y}>{y}</option>)}</select></label><label>Año de análisis<select className="control" value={actual} onChange={e=>{const y=Number(e.target.value);setActual(y);if(base>=y)setBase(y-1);}}>{años.slice(1).map(y=><option key={y}>{y}</option>)}</select></label><label>Contenido del mapa<select className="control" value={verCambio?"cambio":"nivel"} onChange={e=>{setVerCambio(e.target.value==="cambio");setModo("2d");}}><option value="nivel">Nivel del año</option><option value="cambio">Cambio absoluto entre años</option></select></label><label>Métrica del mapa<select className="control" disabled={verCambio} value={tasa?'tasa':'conteo'} onChange={e=>setTasa(e.target.value==='tasa')}><option value="conteo">Registros del año</option><option value="tasa">Tasa anual /100 mil</option></select></label></div>
 {!r?<p role="status">Comparación bloqueada: se requieren 32 entidades completas y conciliación exacta con la serie nacional.</p>:<><div className="impacto-kpis"><article><span>Cambio nacional · {base} → {actual}</span><strong><CambioVisual valor={r.diferencia}/></strong><small>{f(cambio(r.actual,r.base))} % · registros absolutos</small></article><article><span>Entidades con descenso</span><strong>{filas.filter(x=>x.diferencia!<0).length}/32</strong><small>La suma de diferencias estatales coincide con la nacional.</small></article><article><span>Entidades con aumento</span><strong>{filas.filter(x=>x.diferencia!>0).length}/32</strong><small>{filas.filter(x=>x.diferencia===0).length} sin cambio</small></article></div>
 <div className="tarjeta impacto-panel"><h3>{sn.jerarquia[delito].subtipo} · {actual}</h3>{geo&&<MapaMx territorios={geo.territorios} valores={valores} variacion={verCambio} metrica={!verCambio&&tasa?'tasa':'conteo'} titulo={`Distribución estatal de ${sn.jerarquia[delito].subtipo}`} modo={modo} onModo={setModo}/>}<p className="nota">{verCambio ? `Cambio absoluto ${base} → ${actual}. La escala representa la dirección y magnitud del cambio registrado, no una mejora o deterioro de la seguridad.` : "El mapa muestra el nivel del año elegido; la tabla muestra el cambio. El color y la altura no representan contribuciones a la variación."}</p></div>
 <div className="impacto-tabla"><table><caption>Contribución absoluta al cambio nacional, ordenada de mayor disminución a mayor aumento</caption><thead><tr><th>Entidad</th><th>{base}</th><th>{actual}</th><th>Diferencia</th><th>Cambio %</th><th>Tasa {base}</th><th>Tasa {actual}</th></tr></thead><tbody>{filas.map(x=><tr key={x.cve}><th scope="row">{x.nombre}</th><td>{f(x.base)}</td><td>{f(x.actual)}</td><td><CambioVisual valor={x.diferencia}/></td><td><CambioVisual valor={cambio(x.actual??null,x.base??null)} sufijo=" %"/></td><td>{f(tasaAnual(x.cve,x.base,base))}</td><td>{f(tasaAnual(x.cve,x.actual,actual))}</td></tr>)}</tbody></table></div>
 <button className="boton" onClick={()=>descargarCSV('ni-contribuciones-estatales.csv',['clave','entidad','base','actual','diferencia','tasa_base','tasa_actual'],filas.map(x=>[x.cve,x.nombre,x.base!,x.actual!,x.diferencia!,tasaAnual(x.cve,x.base,base),tasaAnual(x.cve,x.actual,actual)]),{fuente:estatal.meta.fuente,corte:estatal.meta.corte,version:String(estatal.meta.version),delito,base:String(base),actual:String(actual),unidad:'Delitos registrados; tasas anuales por 100 mil habitantes',poblacion:pob.meta.fuente,conciliacion:'32 entidades = nacional en ambos años'})}>Descargar contribuciones</button><p className="nota">Los porcentajes estatales no se promedian. Un aumento en una entidad y un descenso en otra no prueban desplazamiento delictivo.</p></>}
 </section>;
}
